version: '3.8'
services:
  auth-service:
    container_name: auth-service
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    entrypoint: sh -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
    expose:
      - "8000"
    depends_on:
      - postgres
      - redis
      - celery-worker
    networks:
      - common-network
    links:
      - postgres
      - redis

  postgres:
    image: postgres:14.3-alpine
    env_file:
      - .env.docker
    container_name: db
    ports:
      - "5432:5432"
    networks:
      - common-network

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
    networks:
      - common-network

  celery-worker:
    build: .
    container_name: celery-worker
    entrypoint: celery
    command: -A project.celery worker -B --loglevel=info
    networks:
      - common-network
    links:
      - redis
    depends_on:
      - redis

  flower:
    build: .
    entrypoint: celery
    command: -A project.celery flower
    networks:
      - common-network
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"


networks:
  common-network:
    driver: bridge
    external: true
