version: '3.8'
services:
  auth-service:
    container_name: auth-service
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    entrypoint: sh -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
    expose:
      - "8000"
    depends_on:
      - postgres
    networks:
      - common-network
    links:
      - postgres

  postgres:
    image: postgres:14.3-alpine
    env_file:
      - .env.docker
    container_name: db
    ports:
      - "5432:5432"
    networks:
      - common-network


networks:
  common-network:
    driver: bridge
    external: true