version: '3.8'
services:
  django:
    container_name: auth_service
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    entrypoint: sh -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: postgres:14.3-alpine
    env_file:
      - .env.docker
    container_name: db
    ports:
      - "5432:5432"

