# Generated by Django 4.2 on 2023-10-19 12:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TPI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lat", models.FloatField(verbose_name="Широта")),
                ("lon", models.FloatField(verbose_name="Долгота")),
                ("direction", models.TextField(verbose_name="Направление движения")),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_auth.usermodel",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Табло переменной информации",
                "verbose_name_plural": "Список ТПИ",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.TextField(unique=True, verbose_name="API Ключ")),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="Обновлен"),
                ),
                ("expired_at", models.DateField(auto_now=True, verbose_name="Истек")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_auth.usermodel",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Ключ",
                "verbose_name_plural": "API Ключи",
                "ordering": ("created_at",),
            },
        ),
    ]
