# Generated by Django 4.2 on 2023-10-25 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tpi",
            old_name="lat",
            new_name="latitude",
        ),
        migrations.RenameField(
            model_name="tpi",
            old_name="lon",
            new_name="longitude",
        ),
        migrations.RemoveField(
            model_name="apikey",
            name="key",
        ),
        migrations.AddField(
            model_name="apikey",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="apikey",
            name="jwt_token",
            field=models.TextField(blank=True, null=True, verbose_name="JWT Токен"),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="expired_at",
            field=models.DateField(blank=True, null=True, verbose_name="Срок годности"),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
