# Generated by Django 4.2 on 2023-11-23 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_lat_tpi_latitude_rename_lon_tpi_longitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountRequestTpi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Время запроса",
                    ),
                ),
                (
                    "tpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tpi",
                        verbose_name="ТПИ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос",
                "verbose_name_plural": "Список запросов",
                "ordering": ("time",),
            },
        ),
    ]
