# Generated by Django 4.2 on 2023-12-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_countrequesttpi_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tpi",
            name="direction",
        ),
        migrations.RemoveField(
            model_name="tpi",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="tpi",
            name="longitude",
        ),
        migrations.AddField(
            model_name="tpi",
            name="end",
            field=models.TextField(default="", verbose_name="Конец трассы"),
        ),
        migrations.AddField(
            model_name="tpi",
            name="highway",
            field=models.TextField(default="", verbose_name="Номер трассы"),
        ),
        migrations.AddField(
            model_name="tpi",
            name="lat_end",
            field=models.FloatField(default=0.0, verbose_name="Широта конечной точки"),
        ),
        migrations.AddField(
            model_name="tpi",
            name="lat_start",
            field=models.FloatField(default=0.0, verbose_name="Широта ТПИ"),
        ),
        migrations.AddField(
            model_name="tpi",
            name="lon_end",
            field=models.FloatField(default=0.0, verbose_name="Долгота конечной точки"),
        ),
        migrations.AddField(
            model_name="tpi",
            name="lon_start",
            field=models.FloatField(default=0.0, verbose_name="Долгота ТПИ"),
        ),
        migrations.AddField(
            model_name="tpi",
            name="start",
            field=models.TextField(default="", verbose_name="Начало трассы"),
        ),
    ]
