# Generated by Django 4.2 on 2023-12-05 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0005_remove_tpi_direction_remove_tpi_latitude_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tpi",
            unique_together={
                (
                    "user",
                    "lat_start",
                    "lon_start",
                    "lat_end",
                    "lon_end",
                    "start",
                    "end",
                    "highway",
                ),
            },
        ),
        migrations.CreateModel(
            name="BlackListJwt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jwt_token", models.TextField(verbose_name="JWT Токен")),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Ключ",
                "verbose_name_plural": "Черный список ключей",
                "ordering": ("id",),
            },
        ),
    ]
