# Generated by Django 4.2 on 2023-12-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_tpi_unique_together_blacklistjwt"),
    ]

    operations = [
        migrations.AddField(
            model_name="tpi",
            name="composite_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tpi",
            name="end",
            field=models.TextField(verbose_name="Конец трассы"),
        ),
        migrations.AlterField(
            model_name="tpi",
            name="highway",
            field=models.TextField(verbose_name="Номер трассы"),
        ),
        migrations.AlterField(
            model_name="tpi",
            name="lat_end",
            field=models.FloatField(verbose_name="Широта конечной точки"),
        ),
        migrations.AlterField(
            model_name="tpi",
            name="lat_start",
            field=models.FloatField(verbose_name="Широта ТПИ"),
        ),
        migrations.AlterField(
            model_name="tpi",
            name="lon_end",
            field=models.FloatField(verbose_name="Долгота конечной точки"),
        ),
        migrations.AlterField(
            model_name="tpi",
            name="lon_start",
            field=models.FloatField(verbose_name="Долгота ТПИ"),
        ),
        migrations.AlterField(
            model_name="tpi",
            name="start",
            field=models.TextField(verbose_name="Начало трассы"),
        ),
    ]
